```{r}
# imports
library(readr)
library(ggplot2)
library(dplyr)
library(tidymodels)
```

```{r}
# setup data
data = read.csv("islands_data.csv")

data = data[complete.cases(data),]
data = data[!is.na(as.numeric(data$day.7.score)), ]
data = select(data, -X2yr.drug.use)

data$income = gsub("\\$", "", data$income)
data$income = gsub(",", "", data$income)
data$income = as.numeric(data$income)

data$education = gsub("\\University Graduate", "uni", data$education)
data$education = gsub("\\High School Graduate", "hs", data$education)
data$education = gsub("\\High School Grad", "hs", data$education)
data$education = gsub("\\High School", "hs", data$education)
data$education = gsub("\\University", "uni", data$education)
data$education = gsub("\\College Graduate", "uni", data$education)
data$education = gsub("\\Elementary School Student", "elm", data$education)

data$sex = gsub("\\Male", "m", data$sex)
data$sex = gsub("\\male", "m", data$sex)
data$sex = gsub("\\Female", "f", data$sex)
data$sex = gsub("\\female", "f", data$sex)
data$sex = gsub("fem", "f", data$sex)
data$sex = gsub("Fem", "f", data$sex)

data$control...shroom = gsub("control", 0, data$control...shroom)
data$control...shroom = gsub("shroom", 1, data$control...shroom)

data$days.after = -1
data$score = -1

data$after.drug.score = data$before.drug.score - data$after.drug.score
data$day.1.score = data$before.drug.score - as.numeric(data$day.1.score)
data$day.2.score = data$before.drug.score - as.numeric(data$day.2.score)
data$day.7.score = data$before.drug.score - as.numeric(data$day.7.score)
```

```{r}
data_after = data.frame(data)
data_after$score = data_after$after.drug.score
data_after$days.after = 0

data_1 = data.frame(data)
data_1$score = data_1$day.1.score
data_1$days.after = 1

data_2 = data.frame(data)
data_2$score = data_2$day.2.score
data_2$days.after = 2

data_7 = data.frame(data)
data_7$score = data_7$day.7.score
data_7$days.after = 7
```

```{r}
total = rbind(data_after, data_1)
total = rbind(total, data_2)
total = rbind(total, data_7)

total = select(total, -after.drug.score)
total = select(total, -day.1.score)
total = select(total, -day.2.score)
total = select(total, -day.7.score)

print(total)
```

```{r}
lm_spec <-
    linear_reg() %>% 
    set_engine(engine = 'lm') %>% 
    set_mode('regression')

mod <- fit(lm_spec,
            score ~ . -name -occupation -island,
            data = total)

mod %>%
  tidy()


total %>%
  #select(-occupation -island -before.drug.score -education -income -age -sex) %>%
  filter(control...shroom == 0) %>%
  ggplot(aes(x=days.after, y=score)) +
  geom_point() +
  labs(x = "Days after exposure", y="Score Delta From First Try", title="Score Difference in Control Population") +
  geom_smooth(method="lm", level=0.90, formula = y ~ x)

total %>%
  #select(-occupation -island -before.drug.score -education -income -age -sex) %>%
  filter(control...shroom == 1) %>%
  ggplot(aes(x=days.after, y=score)) +
  geom_point() +
  labs(x = "Days after exposure", y="Score Delta From First Try", title="Score Difference in Effected Population") +
  geom_smooth(method="lm", level=0.90, formula = y ~ x)

total %>%
  filter(control...shroom == 1) %>%
  ggplot(aes(x=as.factor(days.after), y=score)) +
  geom_boxplot() +
  labs(x = "Days after exposure", y="Score Delta From First Try", title="Score Difference in Effected Population")

total %>%
  filter(control...shroom == 0) %>%
  ggplot(aes(x=as.factor(days.after), y=score)) +
  geom_boxplot() + 
  labs(x = "Days after exposure", y="Score Delta From First Try", title="Score Difference in Control Population")
```

